appName: dev app
description:

menu:
  - title: test1
    icon:
    path: /pages/test1
    # roles:
    #   - role1
    #   - role2

storyboard:
  - path: /pages/test1
    meta:
      title: 测试页面
      page: /dev/devtest1

  - path: /pages/test2
    meta:
      title: 测试页面
      page: /dev/devtest2
    # children:
    #   - path:
    #     meta:
    #       title:
    #       page:
